download_path: "/mnt/efs/data"
write_path: "/mnt/efs/new_processed"
bucket_name: "nsf-ncar-era5"
start_train_year: 2010
end_train_year: 2010
test_years: 
  - 2011
out_of_sample_years:
  - 2012
dt: 6
pl_folder: "e5.oper.an.pl"
sfc_folder: "e5.oper.an.sfc" 
pl_params:
  - "t"
  - "u"
  - "v"
  - "z"
  - "r"
sfc_params:
  - "tcwv"
  - "msl"
  - "sp"
  - "10u"
  - "10v"
  - "100u"
  - "100v"
  - "2t"
pressure_levels:
  t:
    - 100
    - 250
    - 500
    - 850
    - 900
  u:
    - 100
    - 250
    - 500
    - 850
    - 900
    - 1000
  v:
    - 100
    - 250
    - 500
    - 850
    - 900
    - 1000
  z:
    - 50
    - 100
    - 250
    - 500
    - 850
    - 900
    - 1000
  r:
    - 500
    - 850
